apiVersion: v1
kind: Service
metadata:
  name: matches-service 
spec:
  type: NodePort
  ports:
  - port: 5000          # Port exposed within the cluster
    targetPort: 5000  # Port on the pods
    nodePort: 30000   # Port accessible externally on each node
  selector:
    app: matches  # Select pods with this label